### ISSUE TITLE
Improve "I already have a seed" option in Create Wallet

### ISSUE THREAD

**Issue by epiccurious** [BenWestgate/Bails#60]
Use  less ambiguous dialog, like:
“I want to restore a codex32 backup”

**Comment by BenWestgate** [comment]
![image](https://github.com/BenWestgate/Bails/assets/73506583/9e305454-76ae-47aa-84df-5f0bf6eeea5a)

Fixed with https://github.com/BenWestgate/Bails/commit/faf9604c6bfac0a1d27763549472ad18bf51ef8b

We are going to use the word **"Recover"** because that is what the BIP93 uses and secretcodex website uses and more accurately conveys that the essential functionality returns but not exactly what they had before (metadata is lost)

I recovered my car after the tornado vs I restored my car after the tornado.

If you get bored you can change all mentions of Restore Wallet to Recover wallet.

The only two things that get "Restored" are the seed and the identifier, and everything that derives from that.  The rest is a recovery operation.
